In [1]:
%tensorflow_version 2.x
!pip install bert-for-tf2
!pip install sentencepiece
!pip install tensorflow-addons

     |████████████████████████████████| 40kB 2.1MB/s 
  Created wheel for bert-for-tf2: filename=bert_for_tf2-0.14.1-cp36-none-any.whl size=30083 sha256=e5b1232252626cb236f3666e287ce2b56aa2f5acac385ba7a46120fb6ebf8e6f
  Stored in directory: /root/.cache/pip/wheels/dd/f1/10/861fd7899727e4034293fb1dfef45b00f8cd476d21d3b3821e
  Created wheel for py-params: filename=py_params-0.9.7-cp36-none-any.whl size=7302 sha256=081afb9a6871e935f5dcee130154c914bc1f80e07db799f0fd54883244906f97
  Stored in directory: /root/.cache/pip/wheels/67/f5/19/b461849a50aefdf4bab47c4756596e82ee2118b8278e5a1980
  Created wheel for params-flow: filename=params_flow-0.8.0-cp36-none-any.whl size=15999 sha256=b09d40898fb1bf1a3e90e12cfaa1043204b542cd0d4e10c5bead0876606f8241
  Stored in directory: /root/.cache/pip/wheels/88/41/05/1a9955d1d01575bbd58aab76e22f8c7eeabba905d551576f43
Successfully built bert-for-tf2 py-params params-flow
     |████████████████████████████████| 1.0MB 3.3MB/s 


In [2]:
import tensorflow as tf
import tensorflow_hub as hub
# multi-label hamming loss
import tensorflow_addons as tfa
import bert
from tensorflow.keras.models import  Model
from tqdm import tqdm
import numpy as np
from collections import namedtuple
from sklearn.model_selection import train_test_split
from collections import Counter
from imblearn.over_sampling import RandomOverSampler
from google.colab import files
import os

uploaded = files.upload()
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] ="/content/gcs.json"
os.environ['TFHUB_CACHE_DIR'] ="gs://my-data-bucket-colab/toxic-comments-classification/model"


/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)


Saving gcs.json to gcs.json
User uploaded file "gcs.json" with length 2297 bytes


In [3]:
tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
tf.config.experimental_connect_to_cluster(tpu)
tf.tpu.experimental.initialize_tpu_system(tpu)
# instantiate a distribution strategy
tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)

INFO:tensorflow:Initializing the TPU system: grpc://10.79.170.50:8470


INFO:tensorflow:Initializing the TPU system: grpc://10.79.170.50:8470


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Clearing out eager caches


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Finished initializing TPU system.


INFO:tensorflow:Found TPU system:


INFO:tensorflow:Found TPU system:


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Cores: 8


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Workers: 1


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Num TPU Cores Per Worker: 8


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:CPU:0, CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:0, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:1, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:2, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:3, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:4, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:5, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:6, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU:7, TPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


INFO:tensorflow:*** Available Device: _DeviceAttributes(/job:worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 0, 0)


In [0]:

def results(pred_results,ground_truth,threshold):
    pred_results = (pred_results>=threshold).astype(int)
    print("Positive labels RECALL-thre.{}:{}%".format(threshold,100*np.sum(pred_results*ground_truth)/np.sum(ground_truth)))
    cf = tfa.metrics.MultiLabelConfusionMatrix(num_classes=6)
    cf.update_state(ground_truth, pred_results)
    print('Confusion matrix:', cf.result().numpy())
    hl = tfa.metrics.HammingLoss(mode='multilabel', threshold=threshold)
    hl.update_state(ground_truth, pred_results)
    print('Hamming loss:', hl.result().numpy())

def _floats_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value))

def parse_func(s_example):
    features = {
                'labels':tf.io.FixedLenFeature((6,),tf.float32),
                'masks':tf.io.FixedLenFeature((128,),tf.int64),
		            'ids':tf.io.FixedLenFeature((128,),tf.int64),
		            'segments':tf.io.FixedLenFeature((128,),tf.int64),
                }
    example = tf.io.parse_single_example(s_example, features=features)
    return (tf.cast(example['ids'],tf.int32),tf.cast(example['masks'],tf.int32),tf.cast(example['segments'],tf.int32)),example['labels']
def imgSerialization (ids,masks,segments,labels):
    example = tf.train.Example(features=tf.train.Features(feature={
        'labels':_floats_feature(labels),
        'ids':_int64_feature(ids),
	'masks':_int64_feature(masks),
	'segments':_int64_feature(segments)
        }))
    return example.SerializeToString()


In [0]:
def build_model_compile():
    hl = tfa.metrics.HammingLoss(mode='multilabel', threshold=0.4)
    bert_layer=hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1",trainable=False)
    MAX_SEQ_LEN=128
    input_word_ids = tf.keras.layers.Input(shape=(MAX_SEQ_LEN,), dtype=tf.int32,
                                          name="input_word_ids")
    input_mask = tf.keras.layers.Input(shape=(MAX_SEQ_LEN,), dtype=tf.int32,
                                      name="input_mask")
    segment_ids = tf.keras.layers.Input(shape=(MAX_SEQ_LEN,), dtype=tf.int32,
                                        name="segment_ids")
    @tf.function
    def custom_recall(y_true,y_pred):
        y_true = tf.convert_to_tensor(y_true)
        Y_PRED = tf.cast(y_pred>=0.4,tf.float32)
        recall = tf.math.divide_no_nan(tf.math.reduce_sum(tf.math.multiply(y_true,Y_PRED)),tf.math.reduce_sum(y_true))
        return recall
    pooled_output, sequence_output = bert_layer([input_word_ids, input_mask, segment_ids])
    FullTokenizer=bert.bert_tokenization.FullTokenizer
    vocab_file=bert_layer.resolved_object.vocab_file.asset_path.numpy()
    do_lower_case=bert_layer.resolved_object.do_lower_case.numpy()
    tokenizer=FullTokenizer(vocab_file,do_lower_case)
    x = tf.keras.layers.Dropout(0.1)(pooled_output)
    x= tf.keras.layers.Dense(128, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.1)(x)
    out = tf.keras.layers.Dense(6, activation="sigmoid", name="dense_output")(x)

    model = tf.keras.models.Model(
          inputs=[input_word_ids, input_mask, segment_ids], outputs=out)
    model.compile(loss='binary_crossentropy',optimizer='adam',metrics=[hl,custom_recall])

    return model

In [6]:
with tpu_strategy.scope():
  model = build_model_compile()

#bert_layer,model = build_model_compile()
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_word_ids (InputLayer)     [(None, 128)]        0                                            
__________________________________________________________________________________________________
input_mask (InputLayer)         [(None, 128)]        0                                            
__________________________________________________________________________________________________
segment_ids (InputLayer)        [(None, 128)]        0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        [(None, 768), (None, 109482241   input_word_ids[0][0]             
                                                                 input_mask[0][0]             

In [7]:
    
BATCH_SIZE=256
train_dataset = tf.data.Dataset.list_files('gs://my-data-bucket-colab/toxic-comments-classification/train-resampled-label-?.tfrecords').\
        interleave(tf.data.TFRecordDataset, cycle_length=6, block_length=1).map(parse_func).\
        repeat().shuffle(2000).batch(BATCH_SIZE,drop_remainder=True)
model.fit(train_dataset,epochs=3, steps_per_epoch=600000//BATCH_SIZE)
#model.save_weights('/content/chkpt')

Epoch 1/3
2343/2343 [==============================] - 133s 57ms/step - custom_recall: 0.7772 - loss: 0.2986 - hamming_loss: 0.1360
Epoch 2/3
2343/2343 [==============================] - 134s 57ms/step - custom_recall: 0.8112 - loss: 0.2722 - hamming_loss: 0.1236
Epoch 3/3
2343/2343 [==============================] - 134s 57ms/step - custom_recall: 0.8205 - loss: 0.2647 - hamming_loss: 0.1201


In [8]:
test_dataset= tf.data.TFRecordDataset('gs://my-data-bucket-colab/toxic-comments-classification/test.tfrecords').map(parse_func).batch(1024,drop_remainder=True)
pred_results= model.predict(test_dataset)
ground_truth= next(iter(test_dataset.unbatch().batch(40000).map(lambda a, b: b))).numpy().astype(int)
results(pred_results,ground_truth,.4)

Positive labels RECALL-thre.0.4:81.2180517014751%
Confusion matrix: [[[25871.  2917.]
  [  448.  2508.]]

 [[30976.   461.]
  [   95.   212.]]

 [[28229.  1860.]
  [  282.  1373.]]

 [[31545.   100.]
  [   66.    33.]]

 [[28239.  1957.]
  [  265.  1283.]]

 [[30951.   511.]
  [  130.   152.]]]
Hamming loss: 0.047736067


In [0]:
model.save_weights('gs://my-data-bucket-colab/toxic-comments-classification/chkpt')